/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HopeStoriesRouteImport } from './routes/hope-stories'
import { Route as HopeFamilyRouteImport } from './routes/hope-family'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as HopeStoriesIndexRouteImport } from './routes/hope-stories.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as ProjectsSchoolRouteImport } from './routes/projects.school'
import { Route as ProjectsOrphanageRouteImport } from './routes/projects.orphanage'
import { Route as ProjectsMedicalCentreRouteImport } from './routes/projects.medical-centre'
import { Route as ProjectsHopeProjectsRouteImport } from './routes/projects.hope-projects'
import { Route as HopeStoriesOnlineLaunchRouteImport } from './routes/hope-stories.online-launch'
import { Route as AboutOurVisionRouteImport } from './routes/about.our-vision'
import { Route as AboutOurTeamRouteImport } from './routes/about.our-team'
import { Route as AboutKyakaIiRouteImport } from './routes/about.kyaka-ii'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HopeStoriesRoute = HopeStoriesRouteImport.update({
  id: '/hope-stories',
  path: '/hope-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const HopeFamilyRoute = HopeFamilyRouteImport.update({
  id: '/hope-family',
  path: '/hope-family',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const HopeStoriesIndexRoute = HopeStoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HopeStoriesRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const ProjectsSchoolRoute = ProjectsSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsOrphanageRoute = ProjectsOrphanageRouteImport.update({
  id: '/orphanage',
  path: '/orphanage',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsMedicalCentreRoute = ProjectsMedicalCentreRouteImport.update({
  id: '/medical-centre',
  path: '/medical-centre',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsHopeProjectsRoute = ProjectsHopeProjectsRouteImport.update({
  id: '/hope-projects',
  path: '/hope-projects',
  getParentRoute: () => ProjectsRoute,
} as any)
const HopeStoriesOnlineLaunchRoute = HopeStoriesOnlineLaunchRouteImport.update({
  id: '/online-launch',
  path: '/online-launch',
  getParentRoute: () => HopeStoriesRoute,
} as any)
const AboutOurVisionRoute = AboutOurVisionRouteImport.update({
  id: '/our-vision',
  path: '/our-vision',
  getParentRoute: () => AboutRoute,
} as any)
const AboutOurTeamRoute = AboutOurTeamRouteImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => AboutRoute,
} as any)
const AboutKyakaIiRoute = AboutKyakaIiRouteImport.update({
  id: '/kyaka-ii',
  path: '/kyaka-ii',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/hope-family': typeof HopeFamilyRoute
  '/hope-stories': typeof HopeStoriesRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/terms-of-service': typeof TermsOfServiceRoute
  '/about/kyaka-ii': typeof AboutKyakaIiRoute
  '/about/our-team': typeof AboutOurTeamRoute
  '/about/our-vision': typeof AboutOurVisionRoute
  '/hope-stories/online-launch': typeof HopeStoriesOnlineLaunchRoute
  '/projects/hope-projects': typeof ProjectsHopeProjectsRoute
  '/projects/medical-centre': typeof ProjectsMedicalCentreRoute
  '/projects/orphanage': typeof ProjectsOrphanageRoute
  '/projects/school': typeof ProjectsSchoolRoute
  '/about/': typeof AboutIndexRoute
  '/hope-stories/': typeof HopeStoriesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hope-family': typeof HopeFamilyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/about/kyaka-ii': typeof AboutKyakaIiRoute
  '/about/our-team': typeof AboutOurTeamRoute
  '/about/our-vision': typeof AboutOurVisionRoute
  '/hope-stories/online-launch': typeof HopeStoriesOnlineLaunchRoute
  '/projects/hope-projects': typeof ProjectsHopeProjectsRoute
  '/projects/medical-centre': typeof ProjectsMedicalCentreRoute
  '/projects/orphanage': typeof ProjectsOrphanageRoute
  '/projects/school': typeof ProjectsSchoolRoute
  '/about': typeof AboutIndexRoute
  '/hope-stories': typeof HopeStoriesIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/hope-family': typeof HopeFamilyRoute
  '/hope-stories': typeof HopeStoriesRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/terms-of-service': typeof TermsOfServiceRoute
  '/about/kyaka-ii': typeof AboutKyakaIiRoute
  '/about/our-team': typeof AboutOurTeamRoute
  '/about/our-vision': typeof AboutOurVisionRoute
  '/hope-stories/online-launch': typeof HopeStoriesOnlineLaunchRoute
  '/projects/hope-projects': typeof ProjectsHopeProjectsRoute
  '/projects/medical-centre': typeof ProjectsMedicalCentreRoute
  '/projects/orphanage': typeof ProjectsOrphanageRoute
  '/projects/school': typeof ProjectsSchoolRoute
  '/about/': typeof AboutIndexRoute
  '/hope-stories/': typeof HopeStoriesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/hope-family'
    | '/hope-stories'
    | '/privacy-policy'
    | '/projects'
    | '/terms-of-service'
    | '/about/kyaka-ii'
    | '/about/our-team'
    | '/about/our-vision'
    | '/hope-stories/online-launch'
    | '/projects/hope-projects'
    | '/projects/medical-centre'
    | '/projects/orphanage'
    | '/projects/school'
    | '/about/'
    | '/hope-stories/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hope-family'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/about/kyaka-ii'
    | '/about/our-team'
    | '/about/our-vision'
    | '/hope-stories/online-launch'
    | '/projects/hope-projects'
    | '/projects/medical-centre'
    | '/projects/orphanage'
    | '/projects/school'
    | '/about'
    | '/hope-stories'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/hope-family'
    | '/hope-stories'
    | '/privacy-policy'
    | '/projects'
    | '/terms-of-service'
    | '/about/kyaka-ii'
    | '/about/our-team'
    | '/about/our-vision'
    | '/hope-stories/online-launch'
    | '/projects/hope-projects'
    | '/projects/medical-centre'
    | '/projects/orphanage'
    | '/projects/school'
    | '/about/'
    | '/hope-stories/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  HopeFamilyRoute: typeof HopeFamilyRoute
  HopeStoriesRoute: typeof HopeStoriesRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  TermsOfServiceRoute: typeof TermsOfServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hope-stories': {
      id: '/hope-stories'
      path: '/hope-stories'
      fullPath: '/hope-stories'
      preLoaderRoute: typeof HopeStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hope-family': {
      id: '/hope-family'
      path: '/hope-family'
      fullPath: '/hope-family'
      preLoaderRoute: typeof HopeFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/hope-stories/': {
      id: '/hope-stories/'
      path: '/'
      fullPath: '/hope-stories/'
      preLoaderRoute: typeof HopeStoriesIndexRouteImport
      parentRoute: typeof HopeStoriesRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/projects/school': {
      id: '/projects/school'
      path: '/school'
      fullPath: '/projects/school'
      preLoaderRoute: typeof ProjectsSchoolRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/orphanage': {
      id: '/projects/orphanage'
      path: '/orphanage'
      fullPath: '/projects/orphanage'
      preLoaderRoute: typeof ProjectsOrphanageRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/medical-centre': {
      id: '/projects/medical-centre'
      path: '/medical-centre'
      fullPath: '/projects/medical-centre'
      preLoaderRoute: typeof ProjectsMedicalCentreRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/hope-projects': {
      id: '/projects/hope-projects'
      path: '/hope-projects'
      fullPath: '/projects/hope-projects'
      preLoaderRoute: typeof ProjectsHopeProjectsRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/hope-stories/online-launch': {
      id: '/hope-stories/online-launch'
      path: '/online-launch'
      fullPath: '/hope-stories/online-launch'
      preLoaderRoute: typeof HopeStoriesOnlineLaunchRouteImport
      parentRoute: typeof HopeStoriesRoute
    }
    '/about/our-vision': {
      id: '/about/our-vision'
      path: '/our-vision'
      fullPath: '/about/our-vision'
      preLoaderRoute: typeof AboutOurVisionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/our-team': {
      id: '/about/our-team'
      path: '/our-team'
      fullPath: '/about/our-team'
      preLoaderRoute: typeof AboutOurTeamRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/kyaka-ii': {
      id: '/about/kyaka-ii'
      path: '/kyaka-ii'
      fullPath: '/about/kyaka-ii'
      preLoaderRoute: typeof AboutKyakaIiRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutKyakaIiRoute: typeof AboutKyakaIiRoute
  AboutOurTeamRoute: typeof AboutOurTeamRoute
  AboutOurVisionRoute: typeof AboutOurVisionRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutKyakaIiRoute: AboutKyakaIiRoute,
  AboutOurTeamRoute: AboutOurTeamRoute,
  AboutOurVisionRoute: AboutOurVisionRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface HopeStoriesRouteChildren {
  HopeStoriesOnlineLaunchRoute: typeof HopeStoriesOnlineLaunchRoute
  HopeStoriesIndexRoute: typeof HopeStoriesIndexRoute
}

const HopeStoriesRouteChildren: HopeStoriesRouteChildren = {
  HopeStoriesOnlineLaunchRoute: HopeStoriesOnlineLaunchRoute,
  HopeStoriesIndexRoute: HopeStoriesIndexRoute,
}

const HopeStoriesRouteWithChildren = HopeStoriesRoute._addFileChildren(
  HopeStoriesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsHopeProjectsRoute: typeof ProjectsHopeProjectsRoute
  ProjectsMedicalCentreRoute: typeof ProjectsMedicalCentreRoute
  ProjectsOrphanageRoute: typeof ProjectsOrphanageRoute
  ProjectsSchoolRoute: typeof ProjectsSchoolRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsHopeProjectsRoute: ProjectsHopeProjectsRoute,
  ProjectsMedicalCentreRoute: ProjectsMedicalCentreRoute,
  ProjectsOrphanageRoute: ProjectsOrphanageRoute,
  ProjectsSchoolRoute: ProjectsSchoolRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  HopeFamilyRoute: HopeFamilyRoute,
  HopeStoriesRoute: HopeStoriesRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  TermsOfServiceRoute: TermsOfServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
